language: ruby
rvm:
  - 2.2.1
services:
  - postgresql
before_script:
  - psql -c 'create database skylark_test;' -U postgres
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start